Add inbox pagination
ComPlat/chemotion_ELN pull request #1108
Opened 2023-02-01 11:55 UTC by TasnimMehzabin

2023-03-07 15:57 UTC, PiTrem commented on db/schema.rb
> +      CREATE TRIGGER update_users_matrix_trg AFTER INSERT OR UPDATE ON public.matrices FOR EACH ROW EXECUTE FUNCTION update_users_matrix()
?
why the change

2023-05-12 08:41 UTC, adambasha0 approved these changes
already discussed with Tasnim:

- [x] a few linting warning messages to be corrected
- [x]  One bug is fixed (refresh of inbox box, when an attachment is deleted)

Room for improvement for later:
- Add spec tests for existing inbox api

The feature has been tested in the staging server and it is bug-free.

2023-05-17 08:46 UTC, PiTrem requested changes

2023-05-17 08:46 UTC, PiTrem commented on app/api/chemotion/container_api.rb
> +        present @container, with: Entities::ContainerEntity, only: %i[id container_type]
delete should return status 204

2023-06-20 17:34 UTC, PiTrem approved these changes

2023-06-20 17:36 UTC, merged