1110 enhance uiux for cv analyse
ComPlat/chemotion_ELN pull request #1114
Opened 2023-02-06 08:46 UTC by baolanlequang

- [ ] rather 1-story 1-commit than sub-atomic commits

- [ ] commit title is meaningful =>  git history search

- [ ] commit description is helpful => helps the reviewer to understand the changes

- [ ] code is up-to-date with the latest developments of the target branch (rebased to it or whatever) => :fast_forward:-merge for linear history is favoured

- [ ] added code is linted

- [ ] tests are passing (at least locally): we still have some random test failure on CI. thinking of asking spec/examples.txt to be commited

- [ ] in case the changes are visible to the end-user,  video or screenshots should be added to the PR => helps  with user testing

- [ ] testing coverage improvement is improved.

- [ ] CHANGELOG :  add a bullet point on top (optional: reference to github issue/PR )

- [ ] parallele PR for documentation  on docusaurus  if the feature/fix is tagged for a release

2023-02-06 09:08 UTC, baolanlequang commented
Demo video for new UI/UX

https://user-images.githubusercontent.com/9006482/216930680-27479f5b-31cb-4e26-96dd-74b67147be21.mp4

2023-02-22 10:20 UTC, PiTrem commented on app/packs/src/apps/mydb/elements/details/ViewSpectra.js
> +              userManualLink={{cv: 'https://www.chemotion.net/chemotionsaurus/docs/eln/chemspectra/cvanalysis'}}
path to docs has changed :

https://chemotion.net/docs/chemspectra/cv ?

2023-02-22 14:06 UTC, PiTrem commented on app/packs/src/stores/alt/stores/SpectraStore.js
>      const spcMetas = this.decodeSpectra(fetchedFiles);
can it happen that spcMetas is undefined or null?

2023-02-22 14:08 UTC, PiTrem requested changes
link to docu needs an update

also be sure that spcMetas.map does not break things

2023-02-23 09:19 UTC, PiTrem approved these changes

2023-02-23 09:19 UTC, merged