Comment functionality on shared and synchronized collections #699
ComPlat/chemotion_ELN pull request #1237
Opened 2023-03-24 11:15 UTC by TasnimMehzabin

Closes https://github.com/ComPlat/chemotion_ELN/issues/563

2023-06-12 09:19 UTC, adambasha0 requested changes
The review is done, following points were discussed:

- [x] A few minor bugs were fixed:
    - irregular behavior for state update of the comment button color (green/grey) in react comment component
    - inaccurate time of added comments
    - comment notifications mechanism for synchronized collection

- [x] More coverage of spec tests for comment ruby classes is achieved:
   - comment API class: 50.65%
   - comment model: 92.86%
   - comment helpers: 24.0% 
   
- [ ] Requested change: fixing rubocop warning messages for comment_api_spec.rb

Room for improvement:
 - Add js tests for react comment components

2023-06-12 13:02 UTC, PiTrem commented on app/api/chemotion/comment_api.rb
> +      resource :create do
`resource :create` here is superfluous IMO

2023-06-21 09:40 UTC, PiTrem commented on app/api/chemotion/comment_api.rb
> +        before do
should be `after_validation` not `before`

2023-06-26 13:16 UTC, PiTrem approved these changes

2023-06-27 12:40 UTC, merged