fix: fix save wrong combined image
ComPlat/chemotion_ELN pull request #1772
Opened 2024-02-21 10:21 UTC by baolanlequang

- [ ] rather 1-story 1-commit than sub-atomic commits

- [ ] commit title is meaningful =>  git history search

- [ ] commit description is helpful => helps the reviewer to understand the changes

- [ ] code is up-to-date with the latest developments of the target branch (rebased to it or whatever) => :fast_forward:-merge for linear history is favoured

- [ ] added code is linted

- [ ] tests are passing (at least locally): we still have some random test failure on CI. thinking of asking spec/examples.txt to be commited

- [ ] in case the changes are visible to the end-user,  video or screenshots should be added to the PR => helps  with user testing

- [ ] testing coverage improvement is improved.

- [ ] CHANGELOG :  add a bullet point on top (optional: reference to github issue/PR )

- [ ] parallele PR for documentation  on docusaurus  if the feature/fix is tagged for a release

2024-02-29 12:28 UTC, f-idiris approved these changes

2024-03-05 15:26 UTC, PiTrem requested changes

2024-03-05 15:26 UTC, PiTrem commented on app/api/chemotion/chem_spectra_api.rb
> +              bucket: container_id,
rm as it is set automatically

2024-03-05 15:26 UTC, PiTrem commented on app/packs/src/components/container/ContainerDatasetModalContent.js
> +      console.log('attachment.aasm_state', attachment.aasm_state);
rm

2024-03-05 21:17 UTC, merged