Refactor auto inventory label assignment
ComPlat/chemotion_ELN pull request #1818
Opened 2024-03-14 15:07 UTC by adambasha0

- [ ] rather 1-story 1-commit than sub-atomic commits

- [ ] commit title is meaningful =>  git history search

- [ ] commit description is helpful => helps the reviewer to understand the changes

- [ ] code is up-to-date with the latest developments of the target branch (rebased to it or whatever) => :fast_forward:-merge for linear history is favoured

- [ ] added code is linted

- [ ] tests are passing (at least locally): we still have some random test failure on CI. thinking of asking spec/examples.txt to be commited

- [ ] in case the changes are visible to the end-user,  video or screenshots should be added to the PR => helps  with user testing

- [ ] testing coverage improvement is improved.

- [ ] CHANGELOG :  add a bullet point on top (optional: reference to github issue/PR )

- [ ] parallele PR for documentation  on docusaurus  if the feature/fix is tagged for a release

2024-04-08 13:28 UTC, adambasha0 commented
https://github.com/ComPlat/chemotion_ELN/assets/55552142/88808b19-0ed9-4a58-875d-310de34fcfba

2024-04-08 13:30 UTC, adambasha0 commented
https://github.com/ComPlat/chemotion_ELN/assets/55552142/abff157b-f11b-43da-8a8e-fad4d4aa5065

2024-04-21 13:49 UTC, TasnimMehzabin approved these changes

2024-08-19 13:01 UTC, PiTrem requested changes

2024-08-20 12:11 UTC, PiTrem reviewed
more work to be done

2024-08-20 12:15 UTC, merged