Ketcher2 editor
ComPlat/chemotion_ELN pull request #2061
Opened 2024-08-08 08:35 UTC by haditariq

Purpose of this PR is to resolve [Issues # 191](https://github.com/ComPlat/chemotion/issues/191) , [Issues # 199](https://github.com/ComPlat/chemotion/issues/199) 

- (Issue 191) User is provided with a list of global/common templates to use in the ketcher2.
 ***Note: common templates is not complete as you can see when a list of templates is loaded it has a dummy display. That can be fixed using indigo service which is implemented is the other PR so on merge it can be resolved.
 
https://github.com/user-attachments/assets/91a656f6-04e3-438f-aca6-ddfe6944b407

- (Issue 199) Ketcher2 setting are stored for each user as preferences for later effects.

https://github.com/user-attachments/assets/2af9ff08-c2c8-48b9-8574-0b50e76d81f6

---------
- [ ] rather 1-story 1-commit than sub-atomic commits

- [ ] commit title is meaningful =>  git history search

- [ ] commit description is helpful => helps the reviewer to understand the changes

- [ ] code is up-to-date with the latest developments of the target branch (rebased to it or whatever) => :fast_forward:-merge for linear history is favoured

- [ ] added code is linted

- [ ] tests are passing (at least locally): we still have some random test failure on CI. thinking of asking spec/examples.txt to be commited

- [ ] in case the changes are visible to the end-user,  video or screenshots should be added to the PR => helps  with user testing

- [ ] testing coverage improvement is improved.

- [ ] CHANGELOG :  add a bullet point on top (optional: reference to github issue/PR )

- [ ] parallele PR for documentation  on docusaurus  if the feature/fix is tagged for a release

2024-08-16 10:17 UTC, adambasha0 commented on app/api/chemotion/profile_api.rb
> +        File.delete(file_path) if File.exist?(file_path)
use FileUtils.rm_f(file_path) instead

2024-08-16 13:06 UTC, adambasha0 requested changes
- Eslint warnings
- Spec tests for new APIs
- SurfaceChemistry and unused func. into a separate PR
- Documentation for the feature on [Docusaurs](https://chemotion.net/docs/documentation)

2024-08-19 07:53 UTC, haditariq commented on app/packs/src/fetchers/CommonTemplateFetcher.js
> +export default class CommonTemplatesFetcher {
Used at app/packs/src/components/structureEditor/StructureEditorModal.js#L415

2024-08-19 08:11 UTC, haditariq commented on db/seeds/shared/matrice.seed.rb
> +attributes = {
Changed to: ketcher2_matrice.seed.rb

2024-08-19 08:13 UTC, haditariq commented on app/packs/src/components/ketcher-templates/CommonTemplateItem.js
> +  let iconPath = '/images/ketcherails/icons/small/';
It is required for later use with indigo service.

2024-08-19 14:20 UTC, haditariq commented on app/api/chemotion/profile_api.rb
> +          profile.user_templates.each do |template|
This part of code has changed with the implementation approach.

2024-08-19 14:22 UTC, haditariq commented on app/api/chemotion/profile_api.rb
> +          File.new(file_path, 'w') unless File.exist?(file_path)
This part of code has changed with the implementation approach.

2024-08-19 14:22 UTC, haditariq commented on app/api/chemotion/profile_api.rb
> +        new_settings = Ketcher2Setting.create({ user_id: current_user.id }.merge(JSON.parse(params[:data])))
This part of code has changed with the implementation approach.

2024-08-19 20:43 UTC, haditariq commented
- Eslint warnings: Done
- SurfaceChemistry and unused func. into a separate PR: Done

- Documentation for the feature on [Docusaurs](https://chemotion.net/docs/documentation):  Please share details on how it can be done.

User templates and ketcher user settings are re-implemented (usage still same). I'm looking forward to your next review.


@adambasha0

2024-08-23 09:18 UTC, adambasha0 approved these changes

2024-08-23 13:43 UTC, phuang26 commented on 4.json
> +{"resetToSelect":"paste","rotationStep":15,"showValenceWarnings":true,"atomColoring":false,"showStereoFlags":true,"stereoLabelStyle":"Iupac","colorOfAbsoluteCenters":"#ff0000","colorOfAndCenters":"#0
file to be deleted

2024-08-23 13:43 UTC, phuang26 commented on READ_ME_Ketcher2.md
> +    bin/ket2-install.sh
change to chem-ket2-install.sh

2024-08-23 13:43 UTC, phuang26 commented on app/assets/images/svg_icons/shapes.svg
where is this svg being used?

2024-08-23 13:43 UTC, phuang26 commented on app/models/ketcher2_setting.rb
to be deleted

2024-08-23 13:43 UTC, phuang26 commented on db/seeds/shared/ketcher2_matrice.seed.rb
> +attributes = {
to be removed

2024-08-23 13:43 UTC, phuang26 commented on db:seed
> +=> [[32m#<Matrice:0x0000555663b89db8[0m
to be removed

2024-08-23 13:43 UTC, phuang26 commented on public/safety_sheets/131377_Merck.pdf
to be removed

2024-08-23 13:43 UTC, phuang26 commented on public/safety_sheets/252549_Merck.pdf
to be removed

2024-08-23 14:17 UTC, haditariq commented on READ_ME_Ketcher2.md
> +    bin/ket2-install.sh
done

2024-08-23 14:19 UTC, haditariq commented on app/assets/images/svg_icons/shapes.svg
File removed, not used.

2024-08-23 14:20 UTC, haditariq commented on app/models/ketcher2_setting.rb
done

2024-08-23 14:21 UTC, haditariq commented on db/seeds/shared/ketcher2_matrice.seed.rb
> +attributes = {
done

2024-08-23 14:21 UTC, haditariq commented on public/safety_sheets/131377_Merck.pdf
done

2024-08-23 14:21 UTC, haditariq commented on db:seed
> +=> [[32m#<Matrice:0x0000555663b89db8[0m
done

2024-08-23 14:21 UTC, haditariq commented on public/safety_sheets/252549_Merck.pdf
done

2024-08-28 08:26 UTC, merged