Versioning
ComPlat/chemotion_ELN pull request #2068
Opened 2024-08-12 09:43 UTC by PiTrem

2024-10-01 11:51 UTC, JanCBrammer requested changes
I made a few suggestions to revert the changes to semantically unchanged files.
This would make the PR a bit smaller which would make working with the PR in the GitHub UI a bit easier. Atm, the UI is quite unresponsive due to to its size (large diffs in many files).

I'll continue the review over the coming days.

2024-10-01 11:51 UTC, JanCBrammer commented on public/jsmol
I believe this shouldn't be checked in either?

2024-10-01 11:51 UTC, JanCBrammer commented on app/packs/src/stores/alt/actions/ElementActions.js
As far as I can tell there aren't any semantic changes in this file.
Could we revert the changes to make the PR smaller?

2024-10-01 11:51 UTC, JanCBrammer commented on app/packs/src/apps/mydb/elements/details/VersionsTable.js
> +export default class VersionsTable extends Component {
Maybe convert this to a functional component? I feel like introducing new components might be an opportunity to move the codebase away from class components.

2024-10-01 11:51 UTC, JanCBrammer commented on app/packs/src/apps/mydb/elements/details/VersionsTable.js
> +        <BootstrapTable
Maybe use `ag-grid` instead? We already have it in our dependencies.  Even better would be to use a plain `Table` from `react-bootstrap`.

2024-10-02 11:58 UTC, JanCBrammer requested changes

2024-10-02 11:58 UTC, JanCBrammer commented on app/packs/src/models/ResearchPlan.js
Are those changes related to the versioning feature? If not, please revert.

2024-10-02 11:58 UTC, JanCBrammer commented on app/packs/src/models/Sample.js
Are there any semantic / behavioral changes in this diff? If not, please revert.

2024-10-09 10:52 UTC, headri commented on app/models/sample.rb
> +  has_logidze
yes

2024-10-15 05:58 UTC, JanCBrammer commented on app/packs/src/apps/mydb/elements/details/VersionsTableChanges.js
> +    changes.forEach(({ fields }) => {
Use `map` instead of `forEach`? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map

2024-10-15 05:58 UTC, JanCBrammer commented on app/packs/src/apps/mydb/elements/details/VersionsTableChanges.js
> +    alertText += 'Every change is either up to date or irreversible';
Now the first and last conditional branch both contain the "all changes are irreversible" case.

2024-10-23 07:38 UTC, JanCBrammer requested changes
This feature needs tests :monocle_face:

2024-11-08 05:56 UTC, JanCBrammer approved these changes
Tests look ok. Nice that there's at least some basic coverage now.

2024-11-28 08:21 UTC, JanCBrammer reviewed
I tested the latest implementation in the UI. I deleted a starting material from a reaction and saved the reactions. That resulted in two observations that puzzle me a bit:

1. I'd expect the deleted starting material to show up in the "previous version" column, and be absent in the "updated version" column. Not the other way around (like on the screenshot):
![Screenshot from 2024-11-28 09-12-09](https://github.com/user-attachments/assets/18c634d4-872c-4e3d-8d6f-c19ec13294f3)


2. Although I have saved the reaction, a warning indicates that I cannot undo the change due to unsaved changes:
![Screenshot from 2024-11-28 09-09-59](https://github.com/user-attachments/assets/4c065c88-df79-4d33-b1f1-d8c9313b94d3)

2024-12-03 09:13 UTC, JanCBrammer reviewed
@headri and I looked into the the two issues I posted earlier:

1. Seems to be an issue with the UI, not the internal logic. The "previous version column" *does* contain data, but it's only visible on hover-over or when enlarging the column.

2. Happens because the reaction is incorrectly marked as change / unsaved. This problem does not seem to have been introduced with this PR though.

2025-02-20 08:50 UTC, merged