Extend comment box field in analysis tabs for other elements
ComPlat/chemotion_ELN pull request #2241
Opened 2024-11-16 00:51 UTC by adambasha0

- [ ] rather 1-story 1-commit than sub-atomic commits

- [ ] commit title is meaningful =>  git history search

- [ ] commit description is helpful => helps the reviewer to understand the changes

- [ ] code is up-to-date with the latest developments of the target branch (rebased to it or whatever) => :fast_forward:-merge for linear history is favoured

- [ ] added code is linted

- [ ] tests are passing (at least locally): we still have some random test failure on CI. thinking of asking spec/examples.txt to be commited

- [ ] in case the changes are visible to the end-user,  video or screenshots should be added to the PR => helps  with user testing

- [ ] testing coverage improvement is improved.

- [ ] CHANGELOG :  add a bullet point on top (optional: reference to github issue/PR )

- [ ] parallele PR for documentation  on docusaurus  if the feature/fix is tagged for a release

2024-11-20 11:43 UTC, adambasha0 commented
[Chemotion dev (2).webm](https://github.com/user-attachments/assets/c49c5502-db92-412e-9659-bf108b5a76be)

2024-11-26 11:58 UTC, haditariq commented on app/packs/src/components/common/AnalysisCommentBoxComponent.js
> +import React from 'react';
1- Analysis component should not be in common componenets foler. I think calling it a Button would be more fitting. 
2- Exporting 2 indiviual components from one file is not a standard for reusable components.
3- Building a wrapper or individual files would be a nice option.

2024-11-26 12:56 UTC, haditariq requested changes

2024-11-26 12:56 UTC, haditariq commented on app/packs/src/apps/mydb/elements/details/cellLines/analysesTab/AnalysesContainer.js
> +import { CommentButton, CommentBox } from 'src/components/common/AnalysisCommentBoxComponent';
Refactoring requested

2024-11-26 12:56 UTC, haditariq commented on app/packs/src/components/common/AnalysisCommentBoxComponent.js
> +        Add comment
If its a toggle button it should convey user through UI.

2024-11-26 12:56 UTC, haditariq commented on app/packs/src/apps/mydb/elements/details/cellLines/analysesTab/AnalysesContainer.js
> +    currentElement.container.description = e.target.value;
- Is description exists always?
- Checking for valid value before saving and triming the value?

2024-11-26 12:56 UTC, haditariq commented on app/packs/src/apps/mydb/elements/details/reactions/analysesTab/ReactionDetailsContainers.js
> +    reaction.container.description = e.target.value;
Checking value is valid and trimmed before saving

2024-11-26 12:56 UTC, haditariq commented on app/packs/src/components/common/AnalysisCommentBoxComponent.js
> +      <Form.Control
Optional: Have a placeholder for textarea would look nice.

2025-01-07 19:19 UTC, adambasha0 commented on app/packs/src/components/common/AnalysisCommentBoxComponent.js
> +import React from 'react';
I think common folder is suitable for reusable components. Both are closely related, therefore in one file. Building a wrapper that gather both components does not fit here, because both components are called in different positions.

2025-01-07 19:23 UTC, adambasha0 commented on app/packs/src/components/common/AnalysisCommentBoxComponent.js
> +      <Form.Control
done

2025-02-18 10:55 UTC, haditariq commented on app/packs/src/components/common/AnalysisCommentBoxComponent.js
> +        Add comment
@adambasha0 is it in plans to show a visual toggle for example 'remove comment'?

2025-02-18 14:14 UTC, adambasha0 commented on app/packs/src/components/common/AnalysisCommentBoxComponent.js
> +        Add comment
no, not on plan

2025-02-18 14:16 UTC, adambasha0 commented on app/packs/src/apps/mydb/elements/details/reactions/analysesTab/ReactionDetailsContainers.js
> +    reaction.container.description = e.target.value;
no need to, users should be allowed to save comment, as they want to

2025-02-18 14:40 UTC, merged