feat: Incorporate "Gas Scheme" feature in reaction variations table
ComPlat/chemotion_ELN pull request #2250
Opened 2024-12-03 11:41 UTC by JanCBrammer

This PR addresses #2213.
See also https://docs.google.com/document/d/1Jd6V5zqRv0cfw_xAJE-oHDYzSuBMQyBBz3wQQBxRGJo/edit and https://www.chemotion.net/docs/eln/ui/elements/reactions?_highlight=gas#gas-phase-reaction-scheme.

2024-12-20 14:54 UTC, adambasha0 requested changes
Hi Jan, Thanks for the feature. I posted some suggestions and potential bug that you can check later.

2024-12-20 14:54 UTC, adambasha0 commented on app/javascript/src/apps/mydb/elements/details/reactions/variationsTab/ReactionVariationsComponents.js
> +  const { currentEntry, displayUnit } = colDef.entryDefs;
can you check this error? , it happens when I click on duration button: cellData undefined

![image](https://github.com/user-attachments/assets/083c56b3-111a-4a4e-9982-5287b09f0048)

2025-01-07 07:19 UTC, JanCBrammer commented on db/schema.rb
> +ActiveRecord::Schema.define(version: 2024_11_29_093956) do
Changing the timestamp is meant to ensure that we run the migration that's necessary for this PR to work.
See `db/migrate/20241129093956_add_gas_materials_to_reaction_variations.rb`.

2025-01-09 11:33 UTC, JanCBrammer commented on app/javascript/src/apps/mydb/elements/details/reactions/variationsTab/ReactionVariationsComponents.js
> +  const { currentEntry, displayUnit } = colDef.entryDefs;
Do you mean the `duration` entry of a gaseous product?

![image](https://github.com/user-attachments/assets/e2771258-100a-4f98-ae51-a07dd690e106)

What data resulted in the error? For existing data, you might need to run the migration (the one that's part of this PR).

2025-01-09 11:33 UTC, JanCBrammer commented on db/migrate/20241129093956_add_gas_materials_to_reaction_variations.rb
> +  def up
The migration is modifying the `variations` column of the reaction table.
Note that the migration does not add or remove columns in the table.
Instead it updates the existing data in the `variations` column to accommodate the gas feature.
Accommodating the gas feature consists of adding new entries to materials (such as `aux.gasType`).
It also means some restructuring of the materials' data to make the overall data structure more uniform.
The down migration undoes all changes related to the gas feature.

2025-01-09 11:33 UTC, JanCBrammer commented on db/migrate/20241129093956_add_gas_materials_to_reaction_variations.rb
> +            material['aux'].delete('materialType')
I feel like a one-off migration is not the place to save LOC.
In this case I believe it doesn't hurt to keep the code explicit.

2025-01-09 11:33 UTC, JanCBrammer commented on db/migrate/20241129093956_add_gas_materials_to_reaction_variations.rb
> +            material.delete('turnoverNumber')
The reaction-variations data-structure is exclusively handled on the client (JS) side, that's why I stuck with camelCase.

2025-01-09 11:42 UTC, JanCBrammer commented on spec/api/entities/reaction_entity_spec.rb
> -                       products: { '47': { aux: { yield: 0,
Good point, I avoided doing this so far tbh. See bf86a76a0777760b803b94f474eee1a96b7a712d.

2025-01-09 11:43 UTC, JanCBrammer commented on app/api/entities/reaction_variation_entity.rb
> +    expose :duration, if: lambda { |object, _| object[:aux][:gasType] == 'gas' }, using: 'Entities::ReactionVariationMaterialEntryEntity'
See d972f731d68ea3b3904ed310c33a55201627788d. Has the nice side-effect of getting rid of the RuboCop complaints.

2025-01-10 10:43 UTC, adambasha0 commented on db/migrate/20241129093956_add_gas_materials_to_reaction_variations.rb
> +  def up
how did it exist at the first place? - the feature was not there before

2025-01-10 11:52 UTC, JanCBrammer commented on db/migrate/20241129093956_add_gas_materials_to_reaction_variations.rb
> +  def up
I think I don't understand the question. What's "it" referring to?

2025-01-10 11:58 UTC, JanCBrammer commented on spec/api/entities/reaction_entity_spec.rb
> -                       products: { '47': { aux: { yield: 0,
> Did I miss the utilization of reaction_with_variations to test the functionality of updating a value or unit (e.g., in the gas phase) and verifying the recalculation of affected material values or units?

Do the tests under spec/javascripts/packs/src/apps/mydb/elements/details/reactions/variationsTab/ cover what you have in mind?

> ensure the accuracy of values submitted from the client to the server before they are saved in the database?
What do you mean with "accuracy"?

2025-01-14 10:18 UTC, adambasha0 commented on db/migrate/20241129093956_add_gas_materials_to_reaction_variations.rb
> +  def up
how come these attributes (such as: turnoverFrequency, turnoverNumber, concentration, temperature, duration, and gasType) are deleted from the reactions variations, if there are not supposed to be there at the first place?

2025-01-14 13:16 UTC, JanCBrammer commented on db/migrate/20241129093956_add_gas_materials_to_reaction_variations.rb
> +  def up
The attributes related to the gas feature are deleted in the `down` migration because the `down` migration is reverting the `up` migration where they're added.

2025-01-24 07:11 UTC, JanCBrammer commented on app/javascript/src/apps/mydb/elements/details/reactions/variationsTab/ReactionVariationsComponents.js
> +  const { currentEntry, displayUnit } = colDef.entryDefs;
Fixed with #2306.

2025-01-30 10:39 UTC, adambasha0 commented
[Chemotion dev (13).webm](https://github.com/user-attachments/assets/55d90cfa-793d-4805-81a3-227e8a8591f8)
[clicking_on_mmol_triggers_reorder_!.webm](https://github.com/user-attachments/assets/b97b903e-d9f3-4efe-9960-5a00b8df9bb2)

2025-01-30 10:41 UTC, adambasha0 commented
[Chemotion dev (13).webm](https://github.com/user-attachments/assets/391351d8-5519-4047-a03d-4da660d1bc6b)
[clicking_on_mmol_triggers_reorder_!.webm](https://github.com/user-attachments/assets/040815d8-fd08-4dcc-a88d-3fa4331c37aa)

2025-01-30 11:21 UTC, adambasha0 commented
[Chemotion dev (14).webm](https://github.com/user-attachments/assets/3462702e-8267-45f9-a980-76a8f05b5c0f)

2025-01-30 13:41 UTC, adambasha0 commented
sometimes there is miscalculations:
[Chemotion dev (16).webm](https://github.com/user-attachments/assets/36b7e6b5-b3f4-469e-8b0b-f3c4a8ff7cf7)

2025-01-31 08:45 UTC, JanCBrammer reviewed
The review comment pertaining to `Chemotion.dev.13.webm` is:
"when I tried to change the value mmol of feedstock, it did not get changed (sometimes change happens, sometimes not)"

The sorting is enabled for the column that's being changed.
This is why the edited row shifts as soon as the edit is concluded.
Observe how the row IDs shift as soon as the cell edit is concluded.

Unrelated to (but inspired by) the review comment, I observed that the column sorting is in lexicographic order (1, 10, 2), not, as expected in numeric order (1, 2, 10).
I changed the sorting from lexicographic to numeric in 126d6b59bc9f581e49a70fcad23e858fe94e2009.

2025-01-31 09:04 UTC, adambasha0 commented
> The review comment pertaining to `Chemotion.dev.13.webm` and `Chemotion.dev.14.webm` is: "when I tried to change the value mmol of feedstock, it did not get changed (sometimes change happens, sometimes not)"
> 
> The sorting is enabled for the column that's being changed. This is why the edited row shifts as soon as the edit is concluded. Observe how the row IDs shift as soon as the cell edit is concluded.
> 
> Unrelated to (but inspired by) the review comment, I observed that the column sorting is in lexicographic order (1, 10, 2), not, as expected in numeric order (1, 2, 10). I changed the sorting from lexicographic to numeric in [126d6b5](https://github.com/ComPlat/chemotion_ELN/commit/126d6b59bc9f581e49a70fcad23e858fe94e2009).

Hi Jan, thanks for the feedback. I did not notice this. could you provide some info about the arrows and x buttons made for the order functionality on hover over? .. it is not clear to the user what are these buttons expected to d

2025-01-31 09:04 UTC, JanCBrammer reviewed
The review comment pertaining to `Chemotion.dev.15.webm` is:
"When I select one field in a column, and then click on a column header to switch the header >> this leads to false behavior where the initial field value is intact and shown for the wrong column header. Also clicking somewhere else in the table leads to an error"

I fixed the problem in f7f00aea194f3af591c611fcac5cc7c4fc6c71fc according to https://www.ag-grid.com/react-data-grid/cell-editing-start-stop/#stop-editing-when-grid-loses-focus.

2025-01-31 09:05 UTC, adambasha0 commented
styling issues: happens on reload of the page
[Chemotion dev (17).webm](https://github.com/user-attachments/assets/1922f91f-da8e-4433-8a27-5843cfc934ef)

2025-01-31 16:02 UTC, JanCBrammer commented
> styling issues: happens on reload of the page

Fixed with f72fa0ace3051627477fbfd98835d2c19ffa032a.

2025-01-31 16:08 UTC, JanCBrammer commented
> styling issues: happens on reload of the page

Could you elaborate? I'm not quite sure that I fully understand the video.

Note that existing rows in the "Variations" tab does not take over any changes from the "Scheme" tab (in case that's your expectation).

2025-01-31 16:21 UTC, JanCBrammer reviewed
@adambasha0, I've fixed all functional problems you've pointed out, thanks for the thorough review! I'll defer all request regarding styling to the next round of "cosmetic" updates to not bloat this PR any further.

2025-02-17 15:42 UTC, merged