Fixes #500
ComPlat/chemotion_ELN pull request #501
Opened 2021-08-05 12:36 UTC by ptrxyz

2021-08-12 08:28 UTC, PiTrem commented on app/packs/src/components/List.js
> +              <i className={iconClass}></i>
2 vs 4 space indentation

2021-08-24 13:55 UTC, PiTrem requested changes
check indentation should be 2 spaces, no tab

2021-09-19 10:10 UTC, ptrxyz commented
fixed indentation, applied recommended linter settings

2021-09-20 13:55 UTC, PiTrem approved these changes

2021-09-20 14:00 UTC, merged