811 make regerenate edit jdx file button for chem spectra
ComPlat/chemotion_ELN pull request #821
Opened 2022-07-25 07:56 UTC by baolanlequang

- [ ] rather 1-story 1-commit than sub-atomic commits

- [ ] commit title is meaningful =>  git history search

- [ ] commit description is helpful => helps the reviewer to understand the changes

- [ ] code is up-to-date with the latest developments of the target branch (rebased to it or whatever) => :fast_forward:-merge for linear history is favoured

- [ ] added code is linted

- [ ] tests are passing (at least locally): we still have some random test failure on CI. thinking of asking spec/examples.txt to be commited

- [ ] in case the changes are visible to the end-user,  video or screenshots should be added to the PR => helps  with user testing

- [ ] testing coverage improvement is improved.

- [ ] CHANGELOG :  add a bullet point on top (optional: reference to github issue/PR )

- [ ] parallele PR for documentation  on docusaurus  if the feature/fix is tagged for a release

2022-07-25 09:38 UTC, baolanlequang commented
Demo video of this feature

https://user-images.githubusercontent.com/9006482/180746837-3fe9c756-9ccf-447d-a20a-d0ffbbcc4287.mp4

2022-07-29 14:21 UTC, PiTrem requested changes

2022-07-29 14:21 UTC, PiTrem commented on app/api/chemotion/attachment_api.rb
> +        pm[:edited].each do |g_id|
```rb
Attachment.where(id: pm[:edited]).each do |att|
```

2022-07-29 14:21 UTC, PiTrem commented on app/api/chemotion/attachment_api.rb
> +          if can_edit
```
if writable?(att)
```

2022-07-29 14:21 UTC, PiTrem commented on app/api/chemotion/attachment_api.rb
> +            abs_path = att.abs_path
NB: abs_path should not be used
it will have to be changed with the shrine upg
add a todo
```rb
# TODO: do not use abs_path
```

2022-08-04 12:56 UTC, PiTrem commented on app/packs/src/components/SampleDetailsContainersAux.js
> +              <i className="fa fa-refresh" /> Regenerate unoriginal files
better wording needed

2022-11-17 20:49 UTC, merged