Prevent sample-model from unnecessarily updating reaction-SVG
ComPlat/chemotion_ELN pull request #904
Opened 2022-09-07 10:07 UTC by JanCBrammer

Calling `save` on a sample triggers an `after_save` callback in the sample-model that updates the reaction-SVGs that are associated with that sample.

https://github.com/ComPlat/chemotion_ELN/blob/dd3e2c4852ed953b4a89a36dcc1593094e64397a/app/models/sample.rb#L167
https://github.com/ComPlat/chemotion_ELN/blob/dd3e2c4852ed953b4a89a36dcc1593094e64397a/app/models/sample.rb#L511

When a sample is saved in the context of the reaction-API it is not necessary for the sample-model to update the reaction-SVG, since the reaction-model itself updates the reaction-svg.

https://github.com/ComPlat/chemotion_ELN/blob/dd3e2c4852ed953b4a89a36dcc1593094e64397a/app/usecases/reactions/update_materials.rb#L82
https://github.com/ComPlat/chemotion_ELN/blob/dd3e2c4852ed953b4a89a36dcc1593094e64397a/app/models/reaction.rb#L144

The performance of the reaction-API suffers from this, since calling the reaction-API's `post` and `put` endpoints causes the sample-model to carry out unnecessary updates of the reaction-SVG. To improve performance, I prevent the sample-model from updating the reaction-SVG when `sample.save` is called from the reaction-API.

I submit this optimization in preparation of a feature that requires creating multiple reactions in quick succession.
All tests pass locally.

2022-09-07 21:11 UTC, matt-hh requested changes

2022-09-07 21:11 UTC, matt-hh commented on spec/usecases/reactions/update_materials_spec.rb
> +        described_class.new(reaction, starting_materials, user).execute!
All other it-blocks are built with a "given..when..then" structure (aka. "setup..call the method..expect something") except this one ("given..than..when"). It-Blocks are easier to refactor if they follow the same pattern.

```suggestion
        allow(SVG::ReactionComposer).to receive(:new) # this enables the have_received-matcher
        described_class.new(reaction, starting_materials, user).execute!
        expect(SVG::ReactionComposer).to have_received(:new)
```

Let's refactor this spec a little bit in a later step...

2022-09-13 14:45 UTC, matt-hh approved these changes
LGTM!

2022-09-13 14:47 UTC, JanCBrammer commented
@PiTrem, can you merge? @FabianMauz and @matt-hh don't have write access (and hence cannot approve merging) and I cannot approve my own PR it appears :grimacing:

2022-09-13 15:36 UTC, merged